const hot_products = [
  {
    id: 1,
    img: "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P09701_1_l.webp",
    type: "nhóm thần kinh",
    name: "Viên đông trùng hạ thảo Wellness Nutrition (Hộp 90 viên)",
    price: "516,000 VNĐ",
    unit: "Hộp",
  },
  {
    id: 2,
    img: "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P10989_1_l.webp",
    type: "Chăm sóc sức khỏe",
    name: "TPCN bổ não BioCo HuVit Gink forte (Hộp 90 viên)",
    price: "549,000 VNĐ",
    unit: "Hộp",
  },
  {
    id: 3,
    img: "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P22015_1N.jpg",
    type: "Chăm sóc sức khỏe",
    name: "Khẩu trang y tế 3 lớp màu xanh Pharmacity (50 cái/hộp)",
    price: "59,000 VNĐ",
    unit: "Hộp",
  },
  {
    id: 4,
    img: "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P20144_1_l.webp",
    type: "Đẹp da",
    name: "Viên uống Collagen, cấp ẩm Condition Woman (Hộp 90 viên)",
    price: "490,000 VNĐ",
    unit: "Hộp",
  },
  {
    id: 5,
    img: "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P13383_5.jpg",
    type: "Sinh lý nam và nữ",
    name: "Thực phẩm bảo vệ sức khỏe tăng cường sinh lý nam Oyster Plus – Goodhealth (Chai 60 viên)",
    price: "415,000 VNĐ",
    unit: "Chai",
  },
  {
    id: 6,
    img: "https://data-service.pharmacity.io/pmc-upload-media/production/media/promotions/Label%20on%20the%20rightmoidocquyenfreeship.png",
    type: "Sinh lý nam",
    name: "Thực phẩm bảo vệ sức khỏe tăng cường sinh lý ",
    price: "415,000 VNĐ",
    unit: "Chai",
  },
];
